Add smoke tests + save pickled model for KMeans
neptune-ai/neptune-sklearn pull request #12
Opened 2023-01-30 14:35 UTC by twolodzko

* We didn't have any tests for this library, so I added a basic smoke test (log to Neptune + check the basic structure, w/o any detailed chacks).
* When doing the above, I found that we are not saving the pickled model for KMeans. This was trivial to add and I did so.

2023-01-30 14:46 UTC, AleksanderWWW commented
Maybe we could also add running tests to the github workflow?

2023-01-30 14:50 UTC, twolodzko commented
@AleksanderWWW good idea, done.

2023-01-30 15:00 UTC, SiddhantSadangi commented on src/neptune_sklearn/impl/__init__.py
> +    ), "Estimator should be sklearn regressor or classifier."
```suggestion
    ), "Estimator should be sklearn regressor, classifier, or Kmeans instance."
```

2023-02-01 10:11 UTC, kshitij12345 requested changes
I think for dicts it would make sense to wrap them in `stringify_unsupported`.

Also, a lot of docstrings have `neptune.init()` so we may want to update that.

2023-02-01 12:05 UTC, twolodzko commented
@kshitij12345 this PR is not about compatibility with v 1.0.0 but about adding tests. Compatibility issues are fixed in the other ones.

2023-02-01 15:01 UTC, kshitij12345 commented
Noted!

2023-02-06 09:40 UTC, twolodzko commented
@kshitij12345 then can you accept it, or is there anything to change?

2023-02-06 09:49 UTC, kshitij12345 approved these changes
LGTM (on code-front). I am not confident about the CI workflow so would be better that someone else goes through them. (cc: @SiddhantSadangi @AleksanderWWW )

Thank you @twolodzko

2023-02-06 10:06 UTC, AleksanderWWW approved these changes

2023-02-09 16:19 UTC, merged